FROM eclipse-temurin:21-jdk

LABEL "org.opencontainers.image.authors"="https://github.com/mddanish10"

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]
