spring:
  application:
    name: configServer
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mddanish10/microservices-configuration.git"


#        native:
#          search-locations: "classpath:/config"

server:
  port: 8071
